Repository gpx-animator/gpx-animator, pull requests merged in 2023-12, with the labels that each got.

#613 Freeze Option before/after showing photos
  src/main/java/app/gpx_animator/core/Help.java
  src/main/java/app/gpx_animator/core/Option.java
  src/main/java/app/gpx_animator/core/configuration/Configuration.java
  src/main/java/app/gpx_animator/core/renderer/plugins/PhotoPlugin.java
  src/main/java/app/gpx_animator/ui/cli/CommandLineConfigurationFactory.java
  src/main/java/app/gpx_animator/ui/swing/GeneralSettingsPanel.java
  src/main/resources/i18n/Messages.properties
  src/main/resources/i18n/Messages_de.properties
  src/test/java/app/gpx_animator/MemoryAppender.java
  src/test/java/app/gpx_animator/ui/cli/CommandLineIT.java
  src/test/resources/photo/Canon_PowerShot_S40.jpg
Labels: enhancement

#605 #182 add test cli params by enum option
  src/main/java/app/gpx_animator/core/Option.java
  src/main/java/app/gpx_animator/ui/cli/CommandLineConfigurationFactory.java
  src/main/resources/i18n/Messages.properties
  src/main/resources/i18n/Messages_de.properties
  src/test/java/app/gpx_animator/ui/cli/CommandLineConfigurationFactoryTest.java
  src/test/java/app/gpx_animator/ui/cli/OptionParam.java
Labels: maintenance

#620 #619 update gradle
  build.gradle
Labels: maintenance

#626 #625 add plugin maven-publish for create jar.
  build.gradle
Labels: enhancement

#632 #415 set output to input file name if no output is given
  src/main/java/app/gpx_animator/core/configuration/Configuration.java
  src/test/java/app/gpx_animator/ui/cli/CommandLineConfigurationFactoryTest.java
Labels: enhancement

#631 multiple input files on cli with one --input
  src/main/java/app/gpx_animator/ui/cli/CommandLineConfigurationFactory.java
  src/test/java/app/gpx_animator/ui/cli/CommandLineConfigurationFactoryTest.java
Labels: enhancement

#634 #501 add tests for roatating images
  src/test/java/app/gpx_animator/core/renderer/plugins/PhotoPluginTest.java
  src/test/java/app/gpx_animator/core/util/RenderUtilTest.java
  src/test/java/app/gpx_animator/ui/cli/CommandLineIT.java
  src/test/resources/photo/bikeride_rotation_180.jpg
  src/test/resources/photo/directoryWithSinglePhoto/bikeride.jpg
Labels: enhancement

#641 fix npe from photo freeze time when loading old config
  src/main/java/app/gpx_animator/core/configuration/Configuration.java
Labels: bug

#642 adapt scrolling speed
  src/main/java/app/gpx_animator/ui/swing/MainFrame.java
Labels: maintenance

#635 begin and end animation of photo on marker
  src/main/java/app/gpx_animator/core/renderer/plugins/PhotoPlugin.java
Labels: enhancement
